spring:
  config:
    import: classpath:/private.yml
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${private.key.oauth.github.clientId}
            clientSecret: ${private.key.oauth.github.clientSecret}

logging:
  level:
    root: info